export { default as Hero } from './Hero';
export { default as UserPersonas } from './UserPersonas';
export { default as CompatibleApps } from './CompatibleApps';
export { default as HowItWorks } from './HowItWorks';
export { default as Pricing } from './Pricing';
export { default as Benefits } from './Benefits';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as FAQ } from './FAQ'; 